Feats and fixed functions
wppconnect-team/wa-js pull request #1015
Opened 2023-04-01 17:03 UTC by icleitoncosta

- [x] Fixed group doc
- [x] Added WPP.chat.getAllChats with filter
- [ ] Added event for update label (In progress)
- [ ] Improovments on labels funcs

2023-04-07 11:23 UTC, Saifallak commented
Sorry for ping,..
But when you have time @edgardmessias review this,..
Really need it

2023-04-08 20:27 UTC, edgardmessias requested changes

2023-04-08 20:27 UTC, edgardmessias commented on src/chat/functions/getAllChats.ts
> +export function getAllChats(options: GetAllChatsOptions = {}): ChatModel[] {
Dê uma olhada no `WPP.chat.list`, pois basicamente ele é a mesma coisa, talvez seja interessante adicionar a opção de busca lá, como o count e direction

2023-04-08 20:27 UTC, edgardmessias commented on src/chat/events/registerLabelEvent.ts
> +  async function processLabelEvent(event: 'add' | 'remove', ...args: any) {
Talvez aqui seria interessante fazer um teste com o `ChatStore.on()` para capturar os eventos de etiquetas.

Vou fazer mais testes para saber se existe outro ponto melhor.

2023-04-28 01:35 UTC, edgardmessias commented
@icleitoncosta , poderia atualizar essa solicitação e remover o getAllChats?

2023-04-28 02:38 UTC, icleitoncosta commented
> @icleitoncosta , poderia atualizar essa solicitação e remover o getAllChats?

Sim, lembrei dela hje mais cedo, só vou fazer uns ajustes e atualizar

2023-04-28 21:58 UTC, icleitoncosta commented
> @icleitoncosta , poderia atualizar essa solicitação e remover o getAllChats?

Pronto, removi o getAllChats, ainda preciso entender como funciona o rebase pra excluir o commit, vc ja me explicou, mas uma hora sai direito rs

2023-05-01 13:12 UTC, merged

2023-05-13 23:05 UTC, pedromagnox commented
Alguma novidade em relação aos Labels pessoal? Muito complicado de implementar?