feat: More label functions
wppconnect-team/wa-js pull request #154
Opened 2021-12-11 22:38 UTC by ghsgabriel

2021-12-13 12:15 UTC, edgardmessias requested changes
@ghsgabriel muito obrigado, no geral ficou muito bom o que você fez, apenas coloquei a revisão de pequenos ajustes para ficar mais padronizado.

2021-12-13 12:15 UTC, edgardmessias commented on src/labels/Labels.ts
> +    const labels = (await LabelStore._findQuery()) || [];
@ghsgabriel , poderia fazer um teste com a função `find` em fez da `_findQuery`? Pois a `_findQuery` é função mais interna e é chamada pelo `find`

2021-12-13 12:15 UTC, edgardmessias commented on src/labels/Labels.ts
> +   *   ['5541999999999','5541988888888'],
Coloca o exemplo de números com `@c.us`

2021-12-13 12:15 UTC, edgardmessias commented on src/labels/types.ts
> +import { SendMsgResult } from '../whatsapp/enums';
Essa importação não está sendo usada

2021-12-13 12:15 UTC, edgardmessias commented on src/labels/types.ts
> +export interface label {
Renomear para `Label`, assim usando UpperCamelCase

2021-12-13 12:15 UTC, edgardmessias commented on src/labels/types.ts
>  export interface newLabelOptions {
Renomear para `NewLabelOptions`, assim usando UpperCamelCase

2021-12-13 12:15 UTC, edgardmessias commented on src/labels/types.ts
> +export interface addOrRemoveLabelsOptions {
Renomear para `AddOrRemoveLabelsOptions`, assim usando UpperCamelCase

2021-12-13 12:15 UTC, edgardmessias commented on src/whatsapp/collections/LabelCollection.ts
> +  deleteLabel(e?: string): any;
Como que para deletar uma label é obrigatório passar o ID, então pode se remover a interrogação, seria bom também renomear para ficar mais claro
```suggestion
  deleteLabel(id: string): any;
```

2021-12-15 02:14 UTC, ghsgabriel commented on src/labels/Labels.ts
> +    const labels = (await LabelStore._findQuery()) || [];
Coloquei _find(), pois find() retornada erro de id inexistente, tudo bem?

2021-12-15 02:17 UTC, ghsgabriel commented on src/labels/Labels.ts
> +    const labels = (await LabelStore._findQuery()) || [];
@edgardmessias Coloquei _find(), pois find() retornada erro de id inexistente, tudo bem?

2021-12-15 11:02 UTC, merged