fix: Fixed send status error
wppconnect-team/wa-js pull request #1540
Opened 2023-12-08 00:39 UTC by icleitoncosta

![erro ao postar status](https://github.com/wppconnect-team/wa-js/assets/3260480/852cfae0-2bc3-49fb-b35e-bb9be483451d)

Apresentava o seguinte erro ao tentar postar status, fazendo o wrapper dessa função resolveu o mesmo.

2023-12-08 01:20 UTC, edgardmessias requested changes

2023-12-08 01:20 UTC, edgardmessias commented on src/status/functions/sendRawStatus.ts
> +    }
Faltou apenas chamar a função original para outros casos.
```suggestion
    }
    return await func(...args);
```

2023-12-08 11:18 UTC, edgardmessias commented on src/whatsapp/functions/GROUP_JID.ts
> +export declare function GROUP_JID(jid: Wid): Promise<any>;
@icleitoncosta , poderia verificar se essa função é realmente assíncrona, pelo que lembro é uma função normal, talvez tenha que tirar os await/async nos usos.

2023-12-08 15:26 UTC, vphelipe commented
Um forma bem mais elegante seria apenas fazer o wrapper na função que faz a validação do GroupJid e colocar ela pra retornar true se for status@broadcast

2023-12-13 00:02 UTC, edgardmessias commented
@icleitoncosta , só falta ajustar o tipo de função que não é assíncrona para fazer merge desse PR

2023-12-14 23:56 UTC, edgardmessias requested changes
Só falta remover os async/await nos pontos que marquei.

2023-12-14 23:56 UTC, edgardmessias commented on src/status/functions/sendRawStatus.ts
> +  wrapModuleFunction(GROUP_JID, async (func, ...args) => {
```suggestion
  wrapModuleFunction(GROUP_JID, (func, ...args) => {
```

2023-12-14 23:56 UTC, edgardmessias commented on src/status/functions/sendRawStatus.ts
> +      return await CHAT_JID(...args);
```suggestion
      return CHAT_JID(...args);
```

2023-12-14 23:56 UTC, edgardmessias commented on src/status/functions/sendRawStatus.ts
> +    return await func(...args);
```suggestion
    return func(...args);
```

2023-12-15 00:13 UTC, edgardmessias approved these changes

2023-12-15 00:16 UTC, merged