allow sending view once ptt audio messages
wppconnect-team/wa-js pull request #1799
Opened 2024-03-31 09:48 UTC by RustyStriker

seems simply passing forward the isViewOnce in chat.sendFileMessage works for ptt audio messages

2024-03-31 13:49 UTC, icleitoncosta commented
Hello, congratulations on your solution and the commit.
Thank you!

It gave some lint errors, please declare the variable in the AudioMessageOptions interface, in the same file.

2024-04-02 06:47 UTC, RustyStriker commented
@icleitoncosta Done, anything else?

2024-04-02 16:13 UTC, icleitoncosta requested changes

2024-04-02 16:13 UTC, icleitoncosta commented on src/chat/functions/sendFileMessage.ts
> +    if(options.isPtt) {
Add space between if and (.

2024-04-02 16:13 UTC, icleitoncosta commented on src/chat/functions/sendFileMessage.ts
> +
Delete spaces from this lines

2024-05-02 01:06 UTC, closed without merging